server:
  port: 8889
spring:
  application:
    name: code-gen
  profiles:
    active: swagger2
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
